/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1p2_carlosmoncada;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author calol
 */
public class Examen1P2_CarlosMoncada extends javax.swing.JFrame {

    /**
     * Creates new form Examen1P2_CarlosMoncada
     */
    public Examen1P2_CarlosMoncada() {
        initComponents();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_posicion.getModel();
        modelo.addElement("Delantero");
        modelo.addElement("Mediocampista");
        modelo.addElement("Defensa");
        modelo.addElement("Portero");
        cb_posicion.setModel(modelo);
        DefaultComboBoxModel equipo = (DefaultComboBoxModel) cb_equipos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        nacionalidad = new javax.swing.JTextField();
        piehabil = new javax.swing.JTextField();
        btn_agregarjgd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_posicion = new javax.swing.JComboBox<>();
        cb_equipoagregarjgd = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_agregarestadio = new javax.swing.JButton();
        nombre_estadio = new javax.swing.JTextField();
        ciudad_estadio = new javax.swing.JTextField();
        cb_equipos = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        capacidad_estadio = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nombre_equipo = new javax.swing.JTextField();
        pais_equipo = new javax.swing.JTextField();
        bt_agregarequipo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cb_modificarjgd = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cb_posicionmodificar = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        nombre_modificar = new javax.swing.JTextField();
        edad_modifcajgd = new javax.swing.JTextField();
        nacionalidad_modificarjgd = new javax.swing.JTextField();
        btn_modifcar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cb_modificarequipoestadio = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        nombreequipomodificar = new javax.swing.JTextField();
        paisequipomodificar = new javax.swing.JTextField();
        cb_equiposmodificar = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listajugador = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aux_txt = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        cb_eliminar = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        eliminarestadio = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        eliminarequipo = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listarestadio = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Agregar Jugador");

        jLabel2.setText("Nombre");

        jLabel3.setText("Edad");

        jLabel4.setText("Nacionalidad");

        jLabel5.setText("Pie  Habil");

        piehabil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piehabilActionPerformed(evt);
            }
        });

        btn_agregarjgd.setText("Agregar");
        btn_agregarjgd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarjgdMouseClicked(evt);
            }
        });
        btn_agregarjgd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarjgdActionPerformed(evt);
            }
        });

        jLabel6.setText("Posicion");

        cb_posicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_posicionActionPerformed(evt);
            }
        });

        jLabel26.setText("Equipo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre)
                                    .addComponent(edad, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_equipoagregarjgd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                        .addComponent(piehabil))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btn_agregarjgd)))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(piehabil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_equipoagregarjgd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_agregarjgd)
                .addContainerGap())
        );

        tab.addTab("Agregar Jugador a equipo", jPanel1);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Agregar Estadio");

        jLabel8.setText("Nombre");

        jLabel9.setText("Capacidad");

        jLabel10.setText("Ciudad");

        btn_agregarestadio.setText("Agregar Estadio");
        btn_agregarestadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarestadioMouseClicked(evt);
            }
        });
        btn_agregarestadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarestadioActionPerformed(evt);
            }
        });

        jLabel11.setText("Equipo");

        capacidad_estadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacidad_estadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(32, 32, 32)
                                .addComponent(nombre_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ciudad_estadio)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cb_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(capacidad_estadio))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btn_agregarestadio)))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nombre_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(capacidad_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ciudad_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(12, 12, 12)
                .addComponent(btn_agregarestadio)
                .addGap(25, 25, 25))
        );

        tab.addTab("Agregar Estadio", jPanel2);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Agregar Equipo");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Nombre ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Pais");

        pais_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pais_equipoActionPerformed(evt);
            }
        });

        bt_agregarequipo.setText("Agregar equipo");
        bt_agregarequipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarequipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre_equipo, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(pais_equipo)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(bt_agregarequipo)))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nombre_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(pais_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(bt_agregarequipo)
                .addGap(21, 21, 21))
        );

        tab.addTab("Agregar Equipo", jPanel3);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Modificar Jugador");

        jLabel17.setText("Nombre");

        jLabel18.setText("Edad");

        jLabel19.setText("Nacionalidad");

        jLabel20.setText("Posicion");

        edad_modifcajgd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edad_modifcajgdActionPerformed(evt);
            }
        });

        btn_modifcar.setText("Modificar");
        btn_modifcar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modifcarMouseClicked(evt);
            }
        });
        btn_modifcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifcarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cb_modificarjgd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nacionalidad_modificarjgd))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_posicionmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombre_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(edad_modifcajgd)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btn_modifcar)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_modificarjgd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(nombre_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(edad_modifcajgd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(nacionalidad_modificarjgd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_posicionmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_modifcar)
                .addGap(27, 27, 27))
        );

        tab.addTab("Modificar Jugador", jPanel4);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setText("Modificar Estadio");

        jLabel22.setText("Nombre");

        jLabel23.setText("Capacidad");

        jLabel24.setText("Ciudad");

        jLabel25.setText("Equipo");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel21))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jTextField3)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_modificarequipoestadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButton1)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel21)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_modificarequipoestadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        tab.addTab("Modificar Estadio", jPanel5);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Modificar Equipo");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Nombre");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Pais");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Equipo");

        jButton2.setText("Modificar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(66, 66, 66)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(paisequipomodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(nombreequipomodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_equiposmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(282, 282, 282))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(29, 29, 29)
                        .addComponent(nombreequipomodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_equiposmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(paisequipomodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(44, 44, 44))
        );

        tab.addTab("Modificar equipo", jPanel6);

        listajugador.setColumns(20);
        listajugador.setRows(5);
        jScrollPane1.setViewportView(listajugador);

        jLabel30.setText("Equipos");

        jButton3.setText("Listar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        tab.addTab("Listar Equipo", jPanel7);

        aux_txt.setColumns(20);
        aux_txt.setRows(5);
        jScrollPane2.setViewportView(aux_txt);

        jLabel33.setText("Listar jugadores");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel33)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        tab.addTab("Listar Jugadores", jPanel8);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setText("Eliminar jugador");

        cb_eliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_eliminarActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar jugador");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel31))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel31)
                .addGap(26, 26, 26)
                .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        tab.addTab("Eliminar Jugador", jPanel9);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setText("Eliminar Estadio");

        jButton5.setText("Eliminar Estadio");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        eliminarestadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eliminarestadio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addComponent(jLabel32))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(252, 252, 252)
                            .addComponent(jButton5))))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(eliminarestadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton5)
                .addGap(116, 116, 116))
        );

        tab.addTab("Eliminar Estadio", jPanel10);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel34.setText("Eliminar Equipo");

        jButton6.setText("Eliminar equipo");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        eliminarequipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eliminarequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarequipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jLabel34))
                .addGap(294, 294, 294))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(eliminarequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel34)
                .addGap(58, 58, 58)
                .addComponent(eliminarequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        tab.addTab("Eliminar Equipo", jPanel11);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setText("Listar Estadio");

        jToggleButton1.setText("Listar estadio");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        listarestadio.setColumns(20);
        listarestadio.setRows(5);
        jScrollPane3.setViewportView(listarestadio);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToggleButton1)
                            .addComponent(jLabel35)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(101, 101, 101))
        );

        tab.addTab("Listar Estadio", jPanel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void piehabilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piehabilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piehabilActionPerformed

    private void btn_agregarjgdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarjgdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarjgdActionPerformed

    private void btn_agregarjgdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarjgdMouseClicked
        String posicion = (String) cb_posicion.getSelectedItem();
        if (posicion.equalsIgnoreCase("delantero")) {
            Equipo e= new Equipo();
             e=(Equipo)cb_equipoagregarjgd.getSelectedItem();
            if (e.plantilla.size()<4) {
                jugadores.add(new Delantero(nombre.getText(), Integer.parseInt(edad.getText()), "delantero", piehabil.getText(),(Equipo)cb_equipoagregarjgd.getSelectedItem()));
                for (int i = 0; i < equipos.size(); i++) {
                    if (((Equipo)cb_equipoagregarjgd.getSelectedItem()).getNombre().equalsIgnoreCase(equipos.get(i).getNombre())) {
                        equipos.get(i).agregardelantero((Delantero)jugadores.get(jugadores.size()-1));
                    }
                }
            }else{
            JOptionPane.showMessageDialog(this, "no se pueden agregar mas");
            }
            
        } else if (posicion.equalsIgnoreCase("mediocampista")) {
            Equipo e= new Equipo();
             e=(Equipo)cb_equipoagregarjgd.getSelectedItem();
            if (e.plantilla.size()!=4) {
                 jugadores.add(new Mediocampista(nombre.getText(), Integer.parseInt(edad.getText()), "mediocampista", piehabil.getText(),(Equipo)cb_equipoagregarjgd.getSelectedItem()));
            }else{
            JOptionPane.showMessageDialog(this, "no se pueden agregar mas");
            }
           
        } else if (posicion.equalsIgnoreCase("defensa")) {
            Equipo e=(Equipo)cb_equipoagregarjgd.getSelectedItem();
            if (e.plantilla.size()!=4) {
                jugadores.add(new Defensa(nombre.getText(), Integer.parseInt(edad.getText()), "defensa", piehabil.getText(),(Equipo)cb_equipoagregarjgd.getSelectedItem()));
            }else{
            JOptionPane.showMessageDialog(this, "no se pueden agregar mas");
            }
           
        } else if (posicion.equalsIgnoreCase("portero")) {
              Equipo e=(Equipo)cb_equipoagregarjgd.getSelectedItem();
            if (e.plantilla.size()!=4) {
               jugadores.add(new Portero(nombre.getText(), Integer.parseInt(edad.getText()), "defensa", piehabil.getText(),(Equipo)cb_equipoagregarjgd.getSelectedItem()));
            }else{
            JOptionPane.showMessageDialog(this, "no se pueden agregar mas");
            }
           
           
        }
        nombre.setText("");
        edad.setText("");
        piehabil.setText("");
        nacionalidad.setText("");
    }//GEN-LAST:event_btn_agregarjgdMouseClicked

    private void cb_posicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_posicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_posicionActionPerformed

    private void btn_agregarestadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarestadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarestadioActionPerformed


    private void btn_agregarestadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarestadioMouseClicked
       

            Equipo x = new Equipo();

            x = (Equipo) cb_equipos.getSelectedItem();
            estadios.add(new Estadio(nombre_estadio.getText(), ciudad_estadio.getText(), Integer.parseInt(capacidad_estadio.getText()), x));
        
        nombre_estadio.setText("");
        ciudad_estadio.setText("");
        capacidad_estadio.setText("");
    }//GEN-LAST:event_btn_agregarestadioMouseClicked

    private void tabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabStateChanged

        if (tab.getSelectedIndex() == 1 && equipos.size() == 0) {
            JOptionPane.showMessageDialog(this, "No ha añadido equipos,agregaria el estadio sin equipo");
            
        } else if (tab.getSelectedIndex() == 2 && jugadores.size() == 0) {
           
           
        }else if(tab.getSelectedIndex() == 3 && jugadores.size() == 0){
        JOptionPane.showMessageDialog(this, "No ha añadido jugadores no puede modificar");
        
        
        }else if(tab.getSelectedIndex() == 0 && equipos.size()>0){
        DefaultComboBoxModel e= (DefaultComboBoxModel)cb_equipoagregarjgd.getModel();
            for (int i = 0; i < equipos.size(); i++) {
                e.addElement(equipos.get(i));
            }
           cb_equipoagregarjgd.setModel(e);
           
        
        }
        if (tab.getSelectedIndex()==5) {
            DefaultComboBoxModel c=(DefaultComboBoxModel)cb_equiposmodificar.getModel();
            for (int i = 0; i < equipos.size(); i++) {
                c.addElement(equipos.get(i));
            }
            cb_equiposmodificar.setModel(c);
        }
        if (tab.getSelectedIndex() == 1&& equipos.size() > 0) {
            DefaultComboBoxModel equipo = (DefaultComboBoxModel) cb_equipos.getModel();
            for (int i = 0; i < equipos.size(); i++) {
                equipo.addElement(equipos.get(i));
            }
            cb_equipos.setModel(equipo);
        }else if(tab.getSelectedIndex() == 2&& jugadores.size() > 0){
         
        
        }else if(tab.getSelectedIndex() == 3&& jugadores.size() > 0){
            DefaultComboBoxModel modificar= (DefaultComboBoxModel) cb_modificarjgd.getModel();
        for (int i = 0; i < jugadores.size(); i++) {
            modificar.addElement(jugadores.get(i));
        }
       cb_modificarjgd.setModel(modificar);
       DefaultComboBoxModel posicion= (DefaultComboBoxModel)cb_posicionmodificar.getModel();
       posicion.addElement("Delantero");
       posicion.addElement("Mediocampista");
       posicion.addElement("Defensa");
       posicion.addElement("Portero");
       cb_posicionmodificar.setModel(posicion);
        }
        if (tab.getSelectedIndex()==7) {
            String salida="";
            for (int i = 0; i < jugadores.size(); i++) {
                salida+="Jugador :"+jugadores.get(i).nombre+" Posicion :"+jugadores.get(i).nacionalidad+"\n\n";
            }
            aux_txt.setText(salida);
        }
        if (tab.getSelectedIndex()==8) {
           DefaultComboBoxModel c= (DefaultComboBoxModel)cb_eliminar.getModel();
            for (int i = 0; i < jugadores.size(); i++) {
                c.addElement(jugadores.get(i));
            }
            cb_eliminar.setModel(c);
           
         if (tab.getSelectedIndex()==9) {
         DefaultComboBoxModel p= (DefaultComboBoxModel)eliminarestadio.getModel();
            for (int i = 0; i < estadios.size(); i++) {
                p.addElement(estadios.get(i));
            }
            eliminarestadio.setModel(p);
           
        }
         if (tab.getSelectedIndex()==10) {
            DefaultComboBoxModel h= (DefaultComboBoxModel)eliminarequipo.getModel();
            for (int i = 0; i < equipos.size(); i++) {
                h.addElement(equipos.get(i));
            }
            eliminarequipo.setModel(h);
           
        }
        }
         
    }//GEN-LAST:event_tabStateChanged

    private void capacidad_estadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacidad_estadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidad_estadioActionPerformed

    private void pais_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pais_equipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pais_equipoActionPerformed

    private void bt_agregarequipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarequipoMouseClicked
        
        

        
        
            equipos.add(new Equipo(nombre_equipo.getText(), pais_equipo.getText()));
            nombre_equipo.setText("");
            pais_equipo.setText("");

        
    }//GEN-LAST:event_bt_agregarequipoMouseClicked

    private void edad_modifcajgdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edad_modifcajgdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edad_modifcajgdActionPerformed

    private void btn_modifcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifcarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modifcarActionPerformed

    private void btn_modifcarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modifcarMouseClicked
        if (cb_modificarjgd.getSelectedItem() instanceof Delantero) {
            Delantero dc= new Delantero();
            dc=(Delantero)cb_modificarjgd.getSelectedItem();
            for (int i = 0; i < jugadores.size(); i++) {
                if (dc.nombre.equalsIgnoreCase(jugadores.get(i).getNombre())) {
                    jugadores.get(i).setNombre(nombre_modificar.getText());
                    jugadores.get(i).setEdad(Integer.parseInt(edad_modifcajgd.getText()));
                    jugadores.get(i).setNacionalidad(nacionalidad_modificarjgd.getText());
                    jugadores.get(i).setPosicion((String)cb_posicionmodificar.getSelectedItem());
                    
                }
            }
            
        }else if(cb_modificarjgd.getSelectedItem() instanceof Mediocampista){
        Mediocampista mc= new Mediocampista();
            mc=(Mediocampista)cb_modificarjgd.getSelectedItem();
            for (int i = 0; i < jugadores.size(); i++) {
                if (mc.nombre.equalsIgnoreCase(jugadores.get(i).getNombre())) {
                    jugadores.get(i).setNombre(nombre_modificar.getText());
                    jugadores.get(i).setEdad(Integer.parseInt(edad_modifcajgd.getText()));
                    jugadores.get(i).setNacionalidad(nacionalidad_modificarjgd.getText());
                    jugadores.get(i).setPosicion((String)cb_posicionmodificar.getSelectedItem());
                    
                }
            }
        
        }else if(cb_modificarjgd.getSelectedItem() instanceof Defensa){
        Defensa df= new Defensa();
            df=(Defensa)cb_modificarjgd.getSelectedItem();
            for (int i = 0; i < jugadores.size(); i++) {
                if (df.nombre.equalsIgnoreCase(jugadores.get(i).getNombre())) {
                    jugadores.get(i).setNombre(nombre_modificar.getText());
                    jugadores.get(i).setEdad(Integer.parseInt(edad_modifcajgd.getText()));
                    jugadores.get(i).setNacionalidad(nacionalidad_modificarjgd.getText());
                    jugadores.get(i).setPosicion((String)cb_posicionmodificar.getSelectedItem());
                    
                }
            }
        
        }else if(cb_modificarjgd.getSelectedItem() instanceof Portero){
        Portero pt= new Portero();
            pt=(Portero)cb_modificarjgd.getSelectedItem();
            for (int i = 0; i < jugadores.size(); i++) {
                if (pt.nombre.equalsIgnoreCase(jugadores.get(i).getNombre())) {
                    jugadores.get(i).setNombre(nombre_modificar.getText());
                    jugadores.get(i).setEdad(Integer.parseInt(edad_modifcajgd.getText()));
                    jugadores.get(i).setNacionalidad(nacionalidad_modificarjgd.getText());
                    jugadores.get(i).setPosicion((String)cb_posicionmodificar.getSelectedItem());
                    
                }
            }
        
        }
       nombre_modificar.setText("");
       nacionalidad.setText("");
       edad.setText("");
    }//GEN-LAST:event_btn_modifcarMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Equipo e=(Equipo)cb_equiposmodificar.getSelectedItem();
        for (int i = 0; i < equipos.size(); i++) {
            if (e.getNombre().equalsIgnoreCase(equipos.get(i).nombre)) {
                equipos.get(i).setNombre(nombreequipomodificar.getText());
                equipos.get(i).setPais(paisequipomodificar.getText());
            }
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String salida="";
        for (int i = 0; i <equipos.size(); i++) {
            salida+="Posicion "+i+"\nNombre de equipo: "+equipos.get(i).nombre+"\nPais de equipo :"+equipos.get(i).pais+"\n\n";
        }
        listajugador.setText(salida);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_eliminarActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (cb_eliminar.getSelectedItem() instanceof  Delantero) {
            Delantero d=(Delantero)cb_eliminar.getSelectedItem();
            for (int i = 0; i < jugadores.size(); i++) {
                if (d.nombre.equalsIgnoreCase(jugadores.get(i).nombre)) {
                    jugadores.remove(i);
                }
            }
        }else if(cb_eliminar.getSelectedItem() instanceof  Mediocampista){
        Mediocampista d=(Mediocampista)cb_eliminar.getSelectedItem();
            for (int i = 0; i < jugadores.size(); i++) {
                if (d.nombre.equalsIgnoreCase(jugadores.get(i).nombre)) {
                    jugadores.remove(i);
                }
            }
        
        }else if(cb_eliminar.getSelectedItem() instanceof  Defensa){
        Defensa d=(Defensa)cb_eliminar.getSelectedItem();
            for (int i = 0; i < jugadores.size(); i++) {
                if (d.nombre.equalsIgnoreCase(jugadores.get(i).nombre)) {
                    jugadores.remove(i);
                }
            }
        
        }else if(cb_eliminar.getSelectedItem() instanceof  Portero){
        
          Portero d=(Portero)cb_eliminar.getSelectedItem();
            for (int i = 0; i < jugadores.size(); i++) {
                if (d.nombre.equalsIgnoreCase(jugadores.get(i).nombre)) {
                    jugadores.remove(i);
                }
            }
        
        }
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Estadio e= (Estadio)eliminarestadio.getSelectedItem();
        for (int i = 0; i < estadios.size(); i++) {
            if (e.nombre.equalsIgnoreCase(estadios.get(i).nombre)) {
                estadios.remove(i);
            }
        }
        JOptionPane.showMessageDialog(this, "Eliminado correctamente");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void eliminarequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarequipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarequipoActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        Equipo e= new Equipo();
        e=(Equipo)eliminarequipo.getSelectedItem();
        for (int i = 0; i < equipos.size(); i++) {
            if (e.nombre.equalsIgnoreCase(equipos.get(i).nombre)) {
                equipos.remove(i);
            }
        }
        
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        String salida="";
        for (int i = 0; i < estadios.size(); i++) {
            salida+="Nombre"+estadios.get(i).nombre+"  Equipo dueño "+estadios.get(i).equipo+"\n\n";
        }
        listarestadio.setText(salida);
    }//GEN-LAST:event_jToggleButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen1P2_CarlosMoncada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen1P2_CarlosMoncada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen1P2_CarlosMoncada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen1P2_CarlosMoncada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Examen1P2_CarlosMoncada ex= new Examen1P2_CarlosMoncada();
               ex.setLocationRelativeTo(null);
               ex.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aux_txt;
    private javax.swing.JButton bt_agregarequipo;
    private javax.swing.JButton btn_agregarestadio;
    private javax.swing.JButton btn_agregarjgd;
    private javax.swing.JButton btn_modifcar;
    private javax.swing.JFormattedTextField capacidad_estadio;
    private javax.swing.JComboBox<String> cb_eliminar;
    private javax.swing.JComboBox<String> cb_equipoagregarjgd;
    private javax.swing.JComboBox<String> cb_equipos;
    private javax.swing.JComboBox<String> cb_equiposmodificar;
    private javax.swing.JComboBox<String> cb_modificarequipoestadio;
    private javax.swing.JComboBox<String> cb_modificarjgd;
    private javax.swing.JComboBox<String> cb_posicion;
    private javax.swing.JComboBox<String> cb_posicionmodificar;
    private javax.swing.JTextField ciudad_estadio;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField edad_modifcajgd;
    private javax.swing.JComboBox<String> eliminarequipo;
    private javax.swing.JComboBox<String> eliminarestadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextArea listajugador;
    private javax.swing.JTextArea listarestadio;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JTextField nacionalidad_modificarjgd;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombre_equipo;
    private javax.swing.JTextField nombre_estadio;
    private javax.swing.JTextField nombre_modificar;
    private javax.swing.JTextField nombreequipomodificar;
    private javax.swing.JTextField pais_equipo;
    private javax.swing.JTextField paisequipomodificar;
    private javax.swing.JTextField piehabil;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
ArrayList<Jugador> jugadores = new ArrayList();
    ArrayList<Equipo> equipos = new ArrayList();
    ArrayList<Estadio> estadios = new ArrayList();

}
